export enum Routes {
    HOME = '/',
    LOGIN = '/login',
    PASSWORD_FORGOT = '/password/forgot',
    PASSWORD_RESET = '/password/reset',
    PASSWORD_UPDATE = '/password/update',
    USER_REGISTER = '/register',
    USER_MY_PROFILE = '/me',
    USER_UPDATE_PROFILE = '/me/update',
    PRODUCT = '/product',
    CART = '/cart',
    CHECKOUT_STEP_SHIPPING = '/shipping',
    CHECKOUT_STEP_CONFIRM = '/confirm',
    CHECKOUT_STEP_PAYMENT = '/payment',
    CHECKOUT_STEP_SUCCESS = '/success',
    ORDER = "/order",
    ORDER_MY = '/orders/me',
    SEARCH = '/search',

    ADMIN_HOME = '/dashboard',
    ADMIN_ORDER = '/admin/order',
    ADMIN_ORDERS = '/admin/orders',
    ADMIN_PRODUCT = '/admin/product',
    ADMIN_PRODUCTS = '/admin/products',
    ADMIN_REVIEWS = '/admin/reviews',
    ADMIN_USER = '/admin/user',
    ADMIN_USERS = '/admin/users'
};
